language: cpp
compiler: gcc
dist: trusty

before_install:
    # C++17
    - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
    - sudo apt-get update -qq

install:
    # C++17
    - sudo apt-get install -qq g++-6
    - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-6 90
    # Codecov
    - sudo update-alternatives --install /usr/bin/gcov gcov /usr/bin/gcov-6 90
    - sudo pip install codecov

script:
    - for filename in ./codes/*.cpp; do
        ARGS="-std=c++11 -ftest-coverage -fprofile-arcs";
        f=${filename%.*};
        g++ $ARGS -c ${f}.cpp -o ${f}.o;
        g++ $ARGS ${f}.o -o ${f};
        ${f};
        gcov ${f}.cpp;
      done
    - codecov
